=== plvzfq-rit/bettertaguig/src/data/directory/schema/legislative.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Legislative Branch",
  "description": "Schema for municipal legislative council data allowing null for optional fields",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["slug", "branch", "chamber"],
    "properties": {
      "slug": { "type": "string" },
      "branch": { "type": "string" },
      "chamber": { "type": "string" },
      "address": { "type": ["string", "null"] },
      "trunkline": { "type": ["string", "null"] },
      "email": {
        "type": ["string", "null"],
        "format": "email"
      },
      "website": {
        "type": ["string", "null"],
        "format": "uri"
      },
      "officials": {
        "type": "array",
        "items": {
          "type": "object",
          "required": ["role", "name"],
          "properties": {
            "role": { "type": "string" },
            "name": { "type": "string" },
            "contact": { "type": ["string", "null"] },
            "personId": { "type": "string" },
            "website": {
              "type": ["string", "null"],
              "format": "uri"
            }
          }
        }
      },
      "permanent_committees": {
        "type": "array",
        "items": {
          "type": "object",
          "required": ["committee", "chairperson"],
          "properties": {
            "committee": { "type": "string" },
            "chairperson": { "type": "string" },
            "members": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": { "type": ["string", "null"] },
                  "role": { "type": ["string", "null"] }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== plvzfq-rit/bettertaguig/src/data/directory/legislative.json
[
  {
    "slug": "8th-sangguniang-panlungsod",
    "branch": "Legislative Branch",
    "chamber": "8th City Council (Sangguniang Panlungsod ng Taguig)",
    "address": "Sangguniang Panlungsod Legislative Building, City Hall Compound, Barangay Tuktukan, Taguig City / SP Session Hall, 5th-7th Floor, New Taguig City Hall, Cayetano Boulevard, Barangay Ususan, Taguig City",
    "trunkline": null,
    "website": "https://sp.taguig.gov.ph",
    "email": null,
    "officials": [
      {
        "role": "Vice Mayor / Presiding Officer",
        "name": "ARVIN IAN V. ALIT",
        "website": "https://www.facebook.com/ArvinAlit88",
        "personId": "alit-arvin-ian-v"
      },
      {
        "role": "Presiding Officer Pro Tempore / Councilor, 2nd District",
        "name": "MARISSE BALINA-ERON",
        "website": "https://www.facebook.com/MBalinaEron",
        "personId": "balina-eron-marisse"
      },
      {
        "role": "Councilor, 1st District",
        "name": "KIM M. ABBANG",
        "website": "https://web.facebook.com/kimabbang.1978",
        "personId": "abbang-kim-m"
      },
      {
        "role": "Councilor, 1st District",
        "name": "RAUL T. AQUINO",
        "website": "https://www.facebook.com/CouncilorRaulAquino",
        "personId": "aquino-raul-t"
      },
      {
        "role": "Councilor, 1st District",
        "name": "ALLAN PAUL C. CRUZ",
        "website": "https://www.facebook.com/allanpaulcruz168",
        "personId": "cruz-allan-paul-c"
      },
      {
        "role": "Councilor, 1st District",
        "name": "ARNOLD J. CRUZ",
        "website": "http://www.facebook.com/sammy.cruz.9026",
        "personId": "cruz-arnold-j"
      },
      {
        "role": "Councilor, 1st District",
        "name": "DARWIN B. ICAY",
        "website": "https://www.facebook.com/darwin.icay",
        "personId": "icay-darwin-b"
      },
      {
        "role": "Councilor, 1st District",
        "name": "JAIME R. LABAMPA",
        "website": "https://www.facebook.com/KonsiJimlab",
        "personId": "labampa-jaime-r"
      },
      {
        "role": "Councilor, 1st District",
        "name": "LAMBERTO M. MAÑOSCA",
        "website": "https://web.facebook.com/NinongTotong",
        "personId": "manosca-lamberto-m"
      },
      {
        "role": "Councilor, 1st District",
        "name": "RODIL C. MARCELINO",
        "website": "https://www.facebook.com/marcelinotikboy",
        "personId": "marcelino-rodil-c"
      },
      {
        "role": "Councilor, 1st District",
        "name": "CARLITO M. OGALINOLA",
        "website": "https://m.facebook.com/serbisyongOGAling",
        "personId": "ogalinola-carlito-m"
      },
      {
        "role": "Councilor, 1st District",
        "name": "FANELLA JOY B. PANGA-CRUZ",
        "website": "https://www.facebook.com/attyjoypangacruz",
        "personId": "panga-cruz-fanella-joy-b"
      },
      {
        "role": "Councilor, 1st District",
        "name": "GAMALIEL N. SAN PEDRO",
        "website": "https://www.facebook.com/gamie.sanpedro",
        "personId": "san-pedro-gamaliel-n"
      },
      {
        "role": "Councilor, 1st District",
        "name": "FERDINAND B. SANTOS",
        "website": null,
        "personId": "santos-ferdinand-b"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "EDGAR VICTOR S. BAPTISTA",
        "website": "https://www.facebook.com/KonsiBaptista",
        "personId": "baptista-edgar-victor-s"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "MARJORIE BERMAS-VILLASIS",
        "website": "https://www.facebook.com/marjorie.t.bermas",
        "personId": "bermas-villasis-marjorie"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "DANILO G. CASTRO",
        "website": "https://www.facebook.com/Kapdanilodannycastro",
        "personId": "castro-danilo-g"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "GRAZIELLE IONY DE LARA-BES",
        "website": null,
        "personId": "de-lara-bes-grazielle-iony"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "ALVINLEEN P. DIZON",
        "website": "https://www.facebook.com/ivie.dizon.official",
        "personId": "dizon-alvinleen-p"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "HANNAH GENELE P. PAU-TIN",
        "website": "https://www.facebook.com/GenPautin.District2.TaguInstagram.PH",
        "personId": "pau-tin-hannah-genele-p"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "ALEX S. PENOLIO",
        "website": "https://www.facebook.com/konsialexpenolio",
        "personId": "penolio-alex-s"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "EDUARDO B. PRADO",
        "website": "https://www.facebook.com/@edbprado",
        "personId": "prado-eduardo-b"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "JOMIL BRYAN C. SERNA",
        "website": "https://www.facebook.com/jomilserna",
        "personId": "serna-jomil-bryan-c"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "NICKY C. SUPAN",
        "website": "https://www.facebook.com/CouncilorNickySupan",
        "personId": "supan-nicky-c"
      },
      {
        "role": "Councilor, 2nd District",
        "name": "EVELYN DELFINA E. VILLAMOR",
        "website": "https://www.facebook.com/CounsBing",
        "personId": "villamor-evelyn-delfina-e"
      },
      {
        "role": "Liga ng mga Barangay (ABC) President / Ex-Officio Councilor",
        "name": "MARIE MARCELINO",
        "website": null,
        "personId": "marcelino-marie"
      },
      {
        "role": "SK Federation President / Ex-Officio Councilor",
        "name": "JOANNA MAE PAGKALINAWAN",
        "website": null,
        "personId": "pagkalinawan-joanna-mae"
      }
    ],
    "permanent_committees": [
      {
        "committee": "Environmental Protection and Ecology",
        "chairperson": "EDUARDO B. PRADO",
        "members": []
      }
    ]
  }
]
